### ISSUE TITLE
Add high quality GIF output

### ISSUE THREAD

**Issue by pke** [fjcaetano/ios-simulator-gif#5]
Thanks for creating this. I helps to remove manual steps.

How about a little improvement to make the output GIF less dithered and much more high quality so that the GIFs really shine in the PR?

The 2-passes described [here](https://cassidy.codes/blog/2017/04/25/ffmpeg-frames-to-gif-optimization/) should be fairly simple to add to this script.

```bash
#!/bin/sh

palette="/tmp/palette.png"

filters="fps=15,scale=320:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$filters,palettegen=stats_mode=diff" -y $palette

ffmpeg -i $1 -i $palette -lavfi "$filters,paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" -y $2
```

**Comment by pke** [comment]
@fjcaetano would you prefer a PR instead?

**Comment by fjcaetano** [comment]
Hi @pke, I'm sorry I lost track of your issue.

I tried applying those changes, but it seems I may have missed something because I couldn't get it to work properly.

The lib is configured to output gifs with 320px of height by default, if your goal is to have better quality gifs, wouldn't it simply be a matter of sending a filter with higher res as parameter?

If you manage to integrate those changes, feel free to open a PR.

**Comment by pke** [comment]
I am currently running a script with the exact code using `./hq-gif.sh /tmp/simulator.mov simulator.gif` and the output is perfect for PRs.
You need a newer ffmpeg for it that supports `paletteuse`.
Sure the resolution could be handed in via additional argument.

**Comment by fjcaetano** [comment]
If you managed to make it work with the lib, I'm more than happy to take a look at a PR.

**Comment by pke** [comment]
Wow!
Will try it out and distribute to the team. 
Thanks a lot!

**Comment by pke** [comment]
@fjcaetano the build is failing atm

**Comment by fjcaetano** [comment]
That's odd. It's probably ffmpeg because there's literally nothing to compile here. Have you tried unlinking and reinstalling ignoring the dependencies?

Unfortunately, homebrew doesn't allow specifying version requirements for dependencies, so it always try to install and upgrade everything to the latest version, which is often unnecessary
